os: osx

env:
  - UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache"

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

git:
  depth: 1

# safelist
branches:
  only:
    - master
    - stable

before_install:
  - chmod a+x ./travis/*.sh

install:
  - npm install
  - ./travis/install.sh

script:
  - ./travis/test.sh

after_failure:
  - cat _test_result.xml

after_script:
  - cat _test.log