os: osx

rvm:
  - 2.1.2

env:
  - UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache"

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

git:
  depth: 1

# safelist
branches:
  only:
    - master
    - stable

before_install:
  - rvm get stable
  - chmod a+x ./travis/*.sh

install:
  - ./travis/install.sh

script:
  - ./travis/test.sh